In [51]:
import pandas as pd

file_path_jsonl = r'C:\Users\acer\Downloads\people_combined.jsonl'

# Read the JSONL file
df = pd.read_json(file_path_jsonl, lines=True)

print(df)

                        profile  \
0  harsha-karunanayake-875636a8
1       sagara-lakmal-3b5634103

                                                 url                 name  \
0  https://www.linkedin.com/in/harsha-karunanayak...  Harsha Karunanayake
1  https://www.linkedin.com/in/sagara-lakmal-3b56...        Sagara Lakmal

                                      description  \
0  Process Improvement Consultant at MAS Holdings
1           Manager - Data Analytics & Governance

                             location followers connections  \
0  Kandy, Central Province, Sri Lanka        2K        500+
1                           Sri Lanka       293         292

                                               about  \
0  Is a Systematic Problem Solver, Ideologist, Pr...
1                                               None

                                          experience  \
0  [{'position': 'Process Improvement Consultant'...
1  [{'position': 'Manager - Data Analytics & Gove...

                                           education  \
0  [{'organisation': 'University of Kelaniya Sri ...
1  [{'organisation': 'University of Colombo Schoo...

                                      certifications  \
0  [{'certification_title': '', 'certification_is...
1  [{'certification_title': 'Learning Data Scienc...

                                        publications  \
0                                                 []
1  [{'publication_title': 'Interpretive Structura...

                                              awards
0                                                 []
1  [{'award_title': 'Awarded Excellence in Academ...

In [52]:
import ast


df['education'] = df['education'].apply(lambda x: json.loads(x) if isinstance(x, str) else x)
# df['education'] = df['education'].apply(ast.literal_eval)

# Create empty lists to store extracted data
profile_names = []
organization_profiles = []
organisation = []
course_details = []
education_description = []
start_times = []
end_times = []

# Iterate through the DataFrame and extract data
for idx, row in df.iterrows():
    name = row['name']
    education_data = row['education']
    
    for edu in education_data:
        profile_names.append(name)
        organization_profiles.append(edu.get("organisation_profile", ""))
        organisation.append(edu.get("organisation", ""))
        course_details.append(edu.get("course_details", ""))
        education_description.append(edu.get("description", ""))
        start_times.append(edu.get("start_time", ""))
        end_times.append(edu.get("end_time", ""))

# Create a DataFrame from the extracted data
extracted_education_df = pd.DataFrame({
    'Profile Name': profile_names,
    'Organization Profile': organization_profiles,
    'Organisation': organisation,
    'Course Details': course_details,
    'Description': education_description,
    'Start Time': start_times,
    'End Time': end_times
})

print(extracted_education_df)

          Profile Name                               Organization Profile  \
0  Harsha Karunanayake  https://www.linkedin.com/school/university-of-...
1  Harsha Karunanayake  https://www.linkedin.com/school/dharmarajacoll...
2        Sagara Lakmal           https://www.linkedin.com/school/ucsc-lk/
3        Sagara Lakmal  https://www.linkedin.com/school/university-of-...
4        Sagara Lakmal              https://www.linkedin.com/school/cima/
5        Sagara Lakmal     https://www.linkedin.com/school/anandacollege/

                                Organisation  \
0           University of Kelaniya Sri Lanka
1                 Dharmaraja College - Kandy
2  University of Colombo School of Computing
3           University of Kelaniya Sri Lanka
4                                       CIMA
5                Ananda College - Colombo 10

                                      Course Details  \
0  Bsc in Management and Information Technology -...
1  Advance level Mathematics Selected for Univers...
2                       Master of Business Analytics
3  BSc in Management & Information Technology, sp...
4  Part Qualified Accounting and Business/Management
5             GCE Advance Level Combined Mathematics

                                         Description Start Time End Time
0  Ideologist & Presenter at Business Hackathon f...       2013     2017
1  International rated player Sri Lanka National ...       2008     2012
2                                                          2021  present
3                             Academic Achievements:       2013     2018
4                                                          2012     2013
5                                                          2003     2011

In [53]:
import ast
import re

# Define a dictionary to map course categories to numeric values
course_category_mapping = {
    'Other': 1,
    'High school': 2,
    'Diploma': 3,
    'Bachelor': 4,
    'Masters': 5,
    'Post Masters': 6  # Assuming this category for courses like Ph.D.
}

# Define keyword lists for each category
course_keywords = {
    'Other': [],
    'High school': ['school', 'college', 'convent', 'vidyalaya','Advance Level','GCE','Ordinary level','GCE Advance Level Combined Mathematics'],
    'Diploma': ['diploma', 'dip'],
    'Bachelor': ['bachelor', 'bsc', 'bcom', 'beng','B.Sc.'],
    'Masters': ['masters', 'msc', 'mba','master'],
    'Post Masters': ['phd', 'pfor', 'mphil']
}

# Function to categorize a course based on its details
def categorize_course(course_details):
    course_details = course_details.lower()
    for category, keywords in course_keywords.items():
        for keyword in keywords:
            if re.search(r'\b' + re.escape(keyword) + r'\b', course_details):
                return category
    return 'Other'  # Default to 'Other' if no category is found


# Apply the categorize_course function to create the 'Course Category' column
extracted_education_df['Course Category'] = extracted_education_df['Course Details'].apply(categorize_course)

# Map the course categories to numeric values
extracted_education_df['Course Category'] = extracted_education_df['Course Category'].map(course_category_mapping)

# Print the updated DataFrame
print(extracted_education_df)

          Profile Name                               Organization Profile  \
0  Harsha Karunanayake  https://www.linkedin.com/school/university-of-...
1  Harsha Karunanayake  https://www.linkedin.com/school/dharmarajacoll...
2        Sagara Lakmal           https://www.linkedin.com/school/ucsc-lk/
3        Sagara Lakmal  https://www.linkedin.com/school/university-of-...
4        Sagara Lakmal              https://www.linkedin.com/school/cima/
5        Sagara Lakmal     https://www.linkedin.com/school/anandacollege/

                                Organisation  \
0           University of Kelaniya Sri Lanka
1                 Dharmaraja College - Kandy
2  University of Colombo School of Computing
3           University of Kelaniya Sri Lanka
4                                       CIMA
5                Ananda College - Colombo 10

                                      Course Details  \
0  Bsc in Management and Information Technology -...
1  Advance level Mathematics Selected for Univers...
2                       Master of Business Analytics
3  BSc in Management & Information Technology, sp...
4  Part Qualified Accounting and Business/Management
5             GCE Advance Level Combined Mathematics

                                         Description Start Time End Time  \
0  Ideologist & Presenter at Business Hackathon f...       2013     2017
1  International rated player Sri Lanka National ...       2008     2012
2                                                          2021  present
3                             Academic Achievements:       2013     2018
4                                                          2012     2013
5                                                          2003     2011

   Course Category
0                4
1                1
2                5
3                4
4                1
5                1

In [54]:
file_path2 = r'C:\Users\acer\Downloads\institutes_sagara_harsha.jsonl'
df_school = pd.read_json(file_path2,lines=True)

print(df_school)
print(df_school.columns)
print(extracted_education_df.columns)

extracted_education_df['Organisation'] = extracted_education_df['Organisation'].str.lower()
df_school['name'] = df_school['name'].str.lower()

# Merge the DataFrames 
merged_df = pd.merge(extracted_education_df,df_school, left_on='Organisation', right_on='name', how='left')

# Print the merged DataFrame
print(merged_df)

                                        name  \
0           University of Kelaniya Sri Lanka
1  University of Colombo School of Computing
2                             Ananda College
3                 Dharmaraja College - Kandy
4                                       CIMA

                                             summary  \
0                                          not-found
1              Pioneer of ICT education in Sri Lanka
2  Ananda College is the largest national buddhis...
3  "අත්තාහි අත්තනෝ නාතෝ" - "Attahi Attano Natho" ...
4          Helping people and businesses to succeed.

                                       url                           industry  \
0  https://www.linkedin.com/redir/redirect                   Higher Education
1  https://www.linkedin.com/redir/redirect                   Higher Education
2  https://www.linkedin.com/redir/redirect  Education Administration Programs
3               https://www.dharmaraja.lk/               Education Management
4               https://www.aicpa-cima.com                         Accounting

                     size         headquaters         type  founded  \
0   1,001-5,000 employees   Kelaniya, Western  Educational     1875
1        51-200 employees  Colombo 7, Western  Educational     2002
2  5,001-10,000 employees  Colomo 10, Western  Educational     1886
3       201-500 employees      Kandy, Central  Educational     1987
4       201-500 employees              London    Nonprofit     1919

                                        specialities specialties
0  research, academic degrees, and professional d...         NaN
1  Undergraduate Degrees, Postgraduate Degrees, E...         NaN
2                                                NaN
3                                                NaN
4              Professional accounting qualification         NaN
Index(['name', 'summary', 'url', 'industry', 'size', 'headquaters', 'type',
       'founded', 'specialities', 'specialties'],
      dtype='object')
Index(['Profile Name', 'Organization Profile', 'Organisation',
       'Course Details', 'Description', 'Start Time', 'End Time',
       'Course Category'],
      dtype='object')
          Profile Name                               Organization Profile  \
0  Harsha Karunanayake  https://www.linkedin.com/school/university-of-...
1  Harsha Karunanayake  https://www.linkedin.com/school/dharmarajacoll...
2        Sagara Lakmal           https://www.linkedin.com/school/ucsc-lk/
3        Sagara Lakmal  https://www.linkedin.com/school/university-of-...
4        Sagara Lakmal              https://www.linkedin.com/school/cima/
5        Sagara Lakmal     https://www.linkedin.com/school/anandacollege/

                                Organisation  \
0           university of kelaniya sri lanka
1                 dharmaraja college - kandy
2  university of colombo school of computing
3           university of kelaniya sri lanka
4                                       cima
5                ananda college - colombo 10

                                      Course Details  \
0  Bsc in Management and Information Technology -...
1  Advance level Mathematics Selected for Univers...
2                       Master of Business Analytics
3  BSc in Management & Information Technology, sp...
4  Part Qualified Accounting and Business/Management
5             GCE Advance Level Combined Mathematics

                                         Description Start Time End Time  \
0  Ideologist & Presenter at Business Hackathon f...       2013     2017
1  International rated player Sri Lanka National ...       2008     2012
2                                                          2021  present
3                             Academic Achievements:       2013     2018
4                                                          2012     2013
5                                                          2003     2011

   Course Category                                       name  \
0                4           university of kelaniya sri lanka
1                1                 dharmaraja college - kandy
2                5  university of colombo school of computing
3                4           university of kelaniya sri lanka
4                1                                       cima
5                1                                        NaN

                                             summary  \
0                                          not-found
1  "අත්තාහි අත්තනෝ නාතෝ" - "Attahi Attano Natho" ...
2              Pioneer of ICT education in Sri Lanka
3                                          not-found
4          Helping people and businesses to succeed.
5                                                NaN

                                       url              industry  \
0  https://www.linkedin.com/redir/redirect      Higher Education
1               https://www.dharmaraja.lk/  Education Management
2  https://www.linkedin.com/redir/redirect      Higher Education
3  https://www.linkedin.com/redir/redirect      Higher Education
4               https://www.aicpa-cima.com            Accounting
5                                      NaN                   NaN

                    size         headquaters         type  founded  \
0  1,001-5,000 employees   Kelaniya, Western  Educational   1875.0
1      201-500 employees      Kandy, Central  Educational   1987.0
2       51-200 employees  Colombo 7, Western  Educational   2002.0
3  1,001-5,000 employees   Kelaniya, Western  Educational   1875.0
4      201-500 employees              London    Nonprofit   1919.0
5                    NaN                 NaN          NaN      NaN

                                        specialities specialties
0  research, academic degrees, and professional d...         NaN
1                                                NaN
2  Undergraduate Degrees, Postgraduate Degrees, E...         NaN
3  research, academic degrees, and professional d...         NaN
4              Professional accounting qualification         NaN
5                                                NaN         NaN

In [55]:
selected_columns_school = ['Profile Name','Course Category','Start Time','End Time','founded','size','headquaters']
df = merged_df[selected_columns_school]

# Print

In [56]:
#country mapping
from geopy.geocoders import Nominatim

def get_country_from_city(city_name):
    geolocator = Nominatim(user_agent="city-to-country")
    location = geolocator.geocode(city_name)

    if location:
        country_name = location.address.split(",")[-1].strip()
        if country_name == "ශ්‍රී ලංකාව இலங்கை":
            country_name = "Sri Lanka"
        return country_name
    else:
        return None


for index, row in df.iterrows():
    city = row['headquaters']  
    country = get_country_from_city(city)

    if country:
        print(f" {country}")
    else:
        print(f"0")

 Sri Lanka
 Sri Lanka
 Sri Lanka
 Sri Lanka
 United Kingdom
 Italia

In [57]:
df['headquaters'] = df['headquaters'].apply(lambda city: get_country_from_city(city))

C:\Users\acer\AppData\Local\Temp\ipykernel_17512\1609472560.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['headquaters'] = df['headquaters'].apply(lambda city: get_country_from_city(city))

In [58]:
from datetime import datetime

current_date = datetime(2023, 1, 31)

# Replace 'present' with the current year
df['End Time'] = df['End Time'].replace('present', current_date.year)

# Replace empty strings and NaN values with zeros
df['Start Time'] = df['Start Time'].replace('', '0')
df['End Time'] = df['End Time'].replace('', '0')

# Encoding the columns as per your specifications
current_year = 2023
df['start_recency_months'] = df['Start Time'].astype(int).apply(lambda x: (current_year - x) * 12)
df['end_recency_months'] = df['End Time'].astype(int).apply(lambda x: (current_year - x) * 12)

size_mapping = {
    '1,000 - employees': 1,
    '1,001-5,000 employees': 2,
    '5,001-10,000 employees': 3,
    '10,001+ employees': 4
}

# Replace NaN values with a default value, in this case, 0
df['size'].fillna('0', inplace=True)
df['school_size'] = df['size'].map(size_mapping)

df['school_age_years'] = 2023 - df['founded']

# Encoding sri_lankan
df['HeadQuaters'] = df['headquaters'].apply(lambda city: 1 if 'Sri Lanka' in city else 0)


# Dropping the original columns that have been encoded
df = df.drop(['Start Time', 'End Time', 'headquaters', 'size'], axis=1)

# Display the encoded DataFrame
print(df)

          Profile Name  Course Category  founded  start_recency_months  \
0  Harsha Karunanayake                4   1875.0                   120
1  Harsha Karunanayake                1   1987.0                   180
2        Sagara Lakmal                5   2002.0                    24
3        Sagara Lakmal                4   1875.0                   120
4        Sagara Lakmal                1   1919.0                   132
5        Sagara Lakmal                1      NaN                   240

   end_recency_months  school_size  school_age_years  HeadQuaters
0                  72          2.0             148.0            1
1                 132          NaN              36.0            1
2                   0          NaN              21.0            1
3                  60          2.0             148.0            1
4                 120          NaN             104.0            0
5                 144          NaN               NaN            0

C:\Users\acer\AppData\Local\Temp\ipykernel_17512\410971757.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['End Time'] = df['End Time'].replace('present', current_date.year)
C:\Users\acer\AppData\Local\Temp\ipykernel_17512\410971757.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Start Time'] = df['Start Time'].replace('', '0')
C:\Users\acer\AppData\Local\Temp\ipykernel_17512\410971757.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['End Time'] = df['End Time'].replace('', '0')
C:\Users\acer\AppData\Local\Temp\ipykernel_17512\410971757.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['start_recency_months'] = df['Start Time'].astype(int).apply(lambda x: (current_year - x) * 12)
C:\Users\acer\AppData\Local\Temp\ipykernel_17512\410971757.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['end_recency_months'] = df['End Time'].astype(int).apply(lambda x: (current_year - x) * 12)
C:\Users\acer\AppData\Local\Temp\ipykernel_17512\410971757.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['size'].fillna('0', inplace=True)
C:\Users\acer\AppData\Local\Temp\ipykernel_17512\410971757.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['school_size'] = df['size'].map(size_mapping)
C:\Users\acer\AppData\Local\Temp\ipykernel_17512\410971757.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['school_age_years'] = 2023 - df['founded']
C:\Users\acer\AppData\Local\Temp\ipykernel_17512\410971757.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['HeadQuaters'] = df['headquaters'].apply(lambda city: 1 if 'Sri Lanka' in city else 0)