In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\acer\anaconda3\lib\site-packages (1.4.4)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\acer\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\acer\anaconda3\lib\site-packages (from pandas) (2022.1)
Requirement already satisfied: numpy>=1.18.5 in c:\users\acer\anaconda3\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: six>=1.5 in c:\users\acer\appdata\roaming\python\python39\site-packages (from python-dateutil>=2.8.1->pandas) (1.15.0)
Note: you may need to restart the kernel to use updated packages.

In [18]:
import pandas as pd


file_path = r'C:\Users\acer\Downloads\test.csv'

# Read the CSV file into a DataFrame
df = pd.read_csv(file_path)


print(df)

                          profile  \
0         sagara-lakmal-3b5634103
1             ganguli-wijewardana
2    harsha-karunanayake-875636a8
3       keshan-uyanahewa-4512988a
4   ishan-wadugodapitiya-75b86011
5      nadun-marandawela-40392526
6                    dehanvithana
7          dinesh-s-sathischandra
8      ashen-sudharshon-4125811a2
9      damith-wannigama-90085a185
10        zeenath-ahamed-3678a4b8
11      senani-sampathge-60a227a0

                                                  url                  name  \
0   https://www.linkedin.com/in/sagara-lakmal-3b56...         Sagara Lakmal
1    https://www.linkedin.com/in/ganguli-wijewardana/  Ganguli Wijewardhana
2   https://www.linkedin.com/in/harsha-karunanayak...   Harsha Karunanayake
3   https://www.linkedin.com/in/keshan-uyanahewa-4...      keshan Uyanahewa
4   https://www.linkedin.com/in/ishan-wadugodapiti...  Ishan Wadugodapitiya
5   https://www.linkedin.com/in/nadun-marandawela-...     Nadun Marandawela
6           https://www.linkedin.com/in/dehanvithana/         Dehan Vithana
7   https://www.linkedin.com/in/dinesh-s-sathischa...  Dinesh Sathischandra
8   https://www.linkedin.com/in/ashen-sudharshon-4...      Ashen Sudharshon
9   https://www.linkedin.com/in/damith-wannigama-9...      Damith Wannigama
10  https://www.linkedin.com/in/zeenath-ahamed-367...        Zeenath Ahamed
11  https://www.linkedin.com/in/senani-sampathge-6...      Senani Sampathge

                                          description  \
0               Manager - Data Analytics & Governance
1   Assistant manager - Operations & Systems Analy...
2      Process Improvement Consultant at MAS Holdings
3             Assistant Manager - HR & Administration
4   Senior SAP S/4 HANA Consultant (Material Manag...
5   Assistant Manager - Engineering and Maintenanc...
6   Manager - Data Science & Analytics at MAS Inti...
7   at MAS | ex Marks & Spencer, Currys, Parexel, ...
8   Senior Executive - Technical operations at MAS...
9   Deputy Head of Business Finance Team at MAS In...
10  Manager - Organization Structure and Design at...
11  CGMA, ACMA(UK) I BBA(Hons) I Senior Management...

                                         location followers connections  \
0                                       Sri Lanka       289         288
1   Colombo District, Western Province, Sri Lanka       444         428
2              Kandy, Central Province, Sri Lanka        2K        500+
3            Colombo, Western Province, Sri Lanka       126         127
4                                             NaN       NaN         NaN
5                                       Sri Lanka        4K        500+
6            Colombo, Western Province, Sri Lanka        5K        500+
7   Colombo District, Western Province, Sri Lanka       717        500+
8   Colombo District, Western Province, Sri Lanka       665        500+
9                                       Sri Lanka       408         409
10                                      Sri Lanka       634        500+
11                                      Sri Lanka       158         155

                                                about  \
0                                                 NaN
1   Highly motivated and accomplished professional...
2   Is a Systematic Problem Solver, Ideologist, Pr...
3   Administrator/ Transportation & logistics/ Bud...
4   Information Technology Solutions Consultant sp...
5   I'm a BEng (Hons) Mechatronics Engineering gra...
6   I believe, I’m a person who can drive change a...
7   • Senior hands-on Analytics/Data Science/BI le...
8                                                 NaN
9   An accounting professional with more than 10+ ...
10                                                NaN
11                                                NaN

                                           experience  \
0   [{'position': 'Manager - Data Analytics & Gove...
1   [{'position': 'Assistant Manager - Operations ...
2   [{'position': 'Process Improvement Consultant'...
3   [{'position': 'Assistant Manager - HR & Admini...
4   [{'position': '', 'organisation': '', 'organis...
5   [{'position': 'Assistant Manager - Engineering...
6   [{'position': 'Manager - Data Science & Analyt...
7   [{'position': 'Lead - Data Engineering & Scien...
8   [{'position': 'Senior Executive - Technical op...
9   [{'position': 'Deputy Head of Business Finance...
10  [{'position': 'Manager - Organization Structur...
11  [{'position': 'Senior Management Accountant', ...

                                            education  \
0   [{'organisation': 'University of Colombo Schoo...
1   [{'organisation': 'University of Kelaniya Sri ...
2   [{'organisation': 'University of Kelaniya Sri ...
3   [{'organisation': 'University College Dublin',...
4   [{'organisation': '', 'organisation_profile': ...
5   [{'organisation': '', 'organisation_profile': ...
6   [{'organisation': 'University of Moratuwa', 'o...
7   [{'organisation': '', 'organisation_profile': ...
8   [{'organisation': 'University of Westminster',...
9   [{'organisation': 'Postgraduate Institute of M...
10  [{'organisation': 'Staffordshire University', ...
11  [{'organisation': 'University of Peradeniya', ...

                                       certifications  \
0   [{'certification_title': 'Learning Data Scienc...
1   [{'certification_title': '', 'certification_is...
2   [{'certification_title': '', 'certification_is...
3                                                 NaN
4                                                 NaN
5   [{'certification_title': '', 'certification_is...
6                                                 NaN
7                                                 NaN
8   [{'certification_title': '', 'certification_is...
9                                                 NaN
10                                                NaN
11                                                NaN

                                         publications  \
0   [{'publication_title': 'Interpretive Structura...
1   [{'publication_title': '', 'publication_link':...
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN

                                               awards
0   [{'award_title': 'Awarded Excellence in Academ...
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5   [{'award_title': "President's Scout", 'award_g...
6                                                 NaN
7                                                 NaN
8   [{'award_title': 'First class BSC. (Hons.) in ...
9                                                 NaN
10                                                NaN
11                                                NaN

In [19]:
print(df.columns)

Index(['profile', 'url', 'name', 'description', 'location', 'followers',
       'connections', 'about', 'experience', 'education', 'certifications',
       'publications', 'awards'],
      dtype='object')

In [23]:
import pandas as pd
import ast


file_path = r'C:\Users\acer\Downloads\test.csv'


df = pd.read_csv(file_path)

# Use ast.literal_eval to safely parse the single-quoted JSON strings
df['experience'] = df['experience'].apply(ast.literal_eval)

# Create empty lists to store extracted data
profile_names = []
organization_profiles = []
positions = []
start_times = []
end_times = []
durations = []

# Iterate through the DataFrame and extract data
for idx, row in df.iterrows():
    name = row['name']  # Get the 'name' 
    experience_data = row['experience']
    
    for exp in experience_data:
        profile_names.append(name)
        organization_profiles.append(exp.get("organisation_profile", ""))
        positions.append(exp.get("position", ""))
        start_times.append(exp.get("start_time", ""))
        end_times.append(exp.get("end_time", ""))
        durations.append(exp.get("duration", ""))

# Create a DataFrame from the extracted data
extracted_data_df = pd.DataFrame({
    'Profile Name': profile_names,
    'Organization Profile': organization_profiles,
    'Position': positions,
    'Start Time': start_times,
    'End Time': end_times,
    'Duration': durations
})

# Define a function to convert duration to months
def duration_to_months(duration):
    if 'year' in duration:
        months = int(duration.split(' ')[0]) * 12
    elif 'month' in duration:
        months = int(duration.split(' ')[0])
    else:
        months = 0
    return months

# Apply the function to the 'Duration' column to calculate duration in months
extracted_data_df['Duration'] = extracted_data_df['Duration'].apply(duration_to_months)

extracted_data_df

            Profile Name                               Organization Profile  \
0          Sagara Lakmal      https://www.linkedin.com/company/mas-holdings
1          Sagara Lakmal           https://www.linkedin.com/company/ndbbank
2          Sagara Lakmal  https://www.linkedin.com/company/dialog-axiata...
3          Sagara Lakmal      https://www.linkedin.com/company/mas-holdings
4   Ganguli Wijewardhana        https://www.linkedin.com/company/mas-kreeda
5   Ganguli Wijewardhana     https://www.linkedin.com/company/mas-intimates
6    Harsha Karunanayake      https://www.linkedin.com/company/mas-holdings
7    Harsha Karunanayake
8    Harsha Karunanayake
9    Harsha Karunanayake
10   Harsha Karunanayake              https://www.linkedin.com/company/hsbc
11      keshan Uyanahewa      https://www.linkedin.com/company/mas-holdings
12  Ishan Wadugodapitiya       https://lk.linkedin.com/company/mas-holdings
13  Ishan Wadugodapitiya  https://www.linkedin.com/company/attune-rizing...
14     Nadun Marandawela      https://www.linkedin.com/company/mas-holdings
15     Nadun Marandawela  https://www.linkedin.com/company/orange-electrics
16         Dehan Vithana     https://www.linkedin.com/company/mas-intimates
17         Dehan Vithana          https://www.linkedin.com/company/aieseclk
18         Dehan Vithana          https://www.linkedin.com/company/unilever
19         Dehan Vithana  https://www.linkedin.com/company/delltechnologies
20         Dehan Vithana
21         Dehan Vithana  https://www.linkedin.com/company/amitabha-mala...
22         Dehan Vithana  https://www.linkedin.com/company/peoples-bank-...
23  Dinesh Sathischandra      https://www.linkedin.com/company/mas-holdings
24  Dinesh Sathischandra              https://www.linkedin.com/company/wgsn
25  Dinesh Sathischandra         https://www.linkedin.com/company/currysplc
26  Dinesh Sathischandra  https://www.linkedin.com/company/marks-and-spe...
27  Dinesh Sathischandra           https://www.linkedin.com/company/parexel
28  Dinesh Sathischandra           https://www.linkedin.com/company/virtusa
29  Dinesh Sathischandra           https://www.linkedin.com/company/kpmg-us
30      Ashen Sudharshon      https://www.linkedin.com/company/mas-holdings
31      Ashen Sudharshon          https://www.linkedin.com/company/unilever
32      Damith Wannigama     https://www.linkedin.com/company/mas-intimates
33      Damith Wannigama   https://www.linkedin.com/company/fentons-limited
34      Damith Wannigama     https://www.linkedin.com/company/ernstandyoung
35        Zeenath Ahamed      https://www.linkedin.com/company/mas-holdings
36        Zeenath Ahamed
37        Zeenath Ahamed
38      Senani Sampathge      https://www.linkedin.com/company/mas-holdings
39      Senani Sampathge     https://www.linkedin.com/company/ernstandyoung

                                             Position Start Time  End Time  \
0               Manager - Data Analytics & Governance   Jan 2023   present
1   Associate Manager - Data Modelling Lead - Corp...   Jun 2021  Jan 2023
2   Senior Executive - Dashboarding and Visualizat...   Oct 2019  Jun 2021
3                          Executive - Data Analytics   Apr 2018  Sep 2019
4   Assistant Manager - Operations and Systems Ana...
5                                              Intern   Sep 2017  Feb 2018
6                      Process Improvement Consultant
7                                          Co-Founder   Aug 2016  Jan 2021
8                             Academic Content Writer   Apr 2019      2021
9                            Lean Enterprise - Intern   Sep 2017  Mar 2018
10           Financial Crime Compliance (FCC) Analyst       2013      2014
11            Assistant Manager - HR & Administration
12                                                      May 2022   present
13                                                      Jun 2018  May 2022
14    Assistant Manager - Engineering and Maintenance
15                                Engineering Trainee   Jul 2013  Nov 2013
16                 Manager - Data Science & Analytics
17  Member Committee Vice President - Talent Manag...
18                        Trainee Electrical Engineer   Oct 2015  Jul 2016
19                                   Brand Ambassador   Oct 2014  Jan 2016
20                                        Team Member
21                                          Volunteer   Nov 2013  Dec 2013
22                                    Staff Assistant   Feb 2012  Mar 2013
23                  Lead - Data Engineering & Science
24                            Data Science Consultant   Mar 2018  Aug 2018
25    Senior Manager - eCommerce Analytics & Insights   May 2017  Feb 2018
26                 Senior Manager - Finance Analytics   Nov 2015  Apr 2017
27            Manager - Business Intelligence Systems
28            Senior Consultant - Business Consulting
29                                 Software Developer   Jan 2003  Apr 2003
30  Senior Executive - Technical opertions at MAS ...
31                                   Buisness analyst   Jul 2015  Jul 2016
32                    Deputy Head of Business Finance   Aug 2019   present
33                                         Accountant   Sep 2016  Jul 2019
34                                   Audit Supervisor   Feb 2013  Aug 2016
35        Manager - Organization Structure and Design
36             Assistant Manager - Strategic Planning
37         Business Analyst / Senior Business Analyst   Jun 2005  Dec 2009
38                       Senior Management Accountant
39                                      Audit Trainee       2013      2014

    Duration
0          9
1         12
2         12
3         12
4          0
5          6
6          0
7         48
8         24
9          7
10        12
11         0
12        12
13        48
14         0
15         5
16         0
17         0
18        10
19        12
20         0
21         2
22        12
23         0
24         6
25        10
26        12
27         0
28         0
29         4
30         0
31        12
32        48
33        24
34        36
35         0
36         0
37        48
38         0
39        12

In [25]:
output_excel_path = 'output.xlsx'
extracted_data_df.to_excel(output_excel_path, index=False)

print(f'DataFrame has been saved to {output_excel_path}')

DataFrame has been saved to output.xlsx